ubuntu:18.04 was deprecated ??? https://github.com/actions/runner-images/issues/6002 it fails as follows
```
Run echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections || echo "failing on ros-ubuntu is OK" # set non interactive tzdata https://stackoverflow.com/questions/8671308/non-interactive-method-for-dpkg-reconfigure-tzdata
E: Unable to correct problems, you have held broken packages.
Error: Process completed with exit code 100.

```

use ros-ubuntu:18.04 instaed